server:
  port: 8000

eureka:
  instance:
    instance-id: zuul-0 #此实例注册到eureka服务端的唯一的实例ID
    prefer-ip-address: true #是否显示IP地址
    leaseRenewalIntervalInSeconds: 10 #eureka客户需要多长时间发送心跳给eureka服务器，表明它仍然活着,默认为30 秒 (与下面配置的单位都是秒)
    leaseExpirationDurationInSeconds: 30 #Eureka服务器在接收到实例的最后一次发出的心跳后，需要等待多久才可以将此实例删除，默认为90秒
  client:
    serviceUrl:
      defaultZone: http://eureka3000.com:3000/eureka,http://eureka3001.com:3001/eureka,http://eureka3002.com:3002/eureka



spring:
  application:
    name: zuul #此实例注册到eureka服务端的name

zuul:
  prefix: /api #前置路径
  ignored-services: "*" #忽略请求   * 全部忽略
  routes:
    power:
      serviceId: server-power
      path: /power/**
    user:
      serviceId: client-user
      path: /user/**
